name: Auto Add Contributor
on:
  pull_request_target:
    types: [closed]
jobs:
  add-contributor:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: plbstl/first-contribution@main
        with:
          pr-merged-msg: >
            @all-contributors please add @{fc-author} for docs
